#!/usr/bin/env python3
"""Derive config.local.yaml from config.yaml for macOS development.

config.local.yaml was originally hand-made by copying config.yaml, which meant it
silently went stale the moment config.yaml grew a new section: `backfill_mode`
was added to four shows and the local file never got it, so a local archive run
fully summarised a daily news show that was supposed to be indexed only.

Deriving it instead makes that impossible. Re-run this whenever config.yaml
changes:

    uv run python scripts/make-local-config.py
"""

from __future__ import annotations

import pathlib
import sys

HEADER = """# GENERATED by scripts/make-local-config.py — do not edit by hand.
# Re-run that script after changing config.yaml, or this file goes stale.
#
# Differences from the deployed config.yaml, all forced by running natively on a
# Mac rather than inside the compose stack:
#   * CouchDB and the digest folder are on localhost / relative paths
#   * ASR uses the small model, to skip a 1.6GB first-run download
#
# Each tier keeps its OpenRouter primary, so a local run still exercises the same
# provider the deployment leads with. Local development needs
# PODAGENT_OPENROUTER_API_KEY only.
#
# Use with:  PODAGENT_CONFIG_FILE=config.local.yaml uv run podcast-agent
"""

#: (old, new, must_match) — must_match=False tolerates the anchor being absent,
#: which keeps the script working as config.yaml evolves.
REPLACEMENTS: list[tuple[str, str, bool]] = [
    # Host services instead of compose service names.
    ("  url: http://couchdb-podcast:5984", "  url: http://127.0.0.1:5984", True),
    # Writable local paths instead of container mounts.
    ("  digest_dir: /data/digests", "  digest_dir: ./data/digests", True),
    ("  work_dir: /data/work", "  work_dir: ./data/work", True),
    # Loopback only; no macvlan on Docker Desktop.
    (
        "  host: 0.0.0.0               # bound to the container's macvlan LAN IP only",
        "  host: 127.0.0.1             # loopback only on the dev machine",
        True,
    ),
    # large-v3-turbo is a 1.6GB first-run download.
    ("  model: large-v3-turbo", "  model: small.en", True),
    # NOTE: the llm section is intentionally absent from this list. Every tier is
    # cloud in config.yaml while there is no local model host, and rewriting it
    # here would mean local runs stopped exercising the deployed configuration.
    # When an Ollama primary is restored in config.yaml, the local overrides that
    # used to live here (127.0.0.1 api_base, the qwen3.5:9b models with
    # think:false, longer timeouts, smaller token budgets) come back with it.
]


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    source = root / "config.yaml"
    target = root / "config.local.yaml"

    text = source.read_text(encoding="utf-8")
    missing: list[str] = []
    for old, new, must_match in REPLACEMENTS:
        if old not in text:
            if must_match:
                missing.append(old.strip().splitlines()[0])
            continue
        text = text.replace(old, new)

    if missing:
        print("config.yaml no longer contains these anchors:", file=sys.stderr)
        for anchor in missing:
            print(f"  {anchor}", file=sys.stderr)
        print("\nUpdate REPLACEMENTS in this script.", file=sys.stderr)
        return 1

    target.write_text(HEADER + "\n" + text, encoding="utf-8")
    print(f"wrote {target.relative_to(root)} from {source.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
