#!/usr/bin/env python3
"""Derive config.local.yaml from config.yaml for macOS development.

config.local.yaml was originally hand-made by copying config.yaml, which meant it
silently went stale the moment config.yaml grew a new section: `backfill_mode`
was added to four shows and the local file never got it, so a local archive run
fully summarised a daily news show that was supposed to be indexed only.

Deriving it instead makes that impossible. Re-run this whenever config.yaml
changes:

    uv run python scripts/make-local-config.py
"""

from __future__ import annotations

import pathlib
import re
import sys

HEADER = """# GENERATED by scripts/make-local-config.py — do not edit by hand.
# Re-run that script after changing config.yaml, or this file goes stale.
#
# Differences from the deployed config.yaml, all forced by running natively on a
# Mac rather than inside the compose stack:
#   * CouchDB and the digest folder are on localhost / relative paths
#   * ASR uses the small model, to skip a 1.6GB first-run download
#   * the Anthropic fallback endpoints are dropped
#
# Each tier keeps its OpenRouter primary, so a local run still exercises the same
# provider the deployment leads with. What it does not do is require a SECOND
# vendor's API key before the process will start: an unset
# PODAGENT_ANTHROPIC_API_KEY is a hard startup failure when an anthropic endpoint
# is in the chain, and paying for a second vendor to run the test suite is not a
# reasonable price of entry. The fallback is a production resilience property;
# losing it locally costs nothing but the chance to exercise a path that only
# runs when OpenRouter is down.
#
# Local development therefore needs PODAGENT_OPENROUTER_API_KEY only.
#
# Use with:  PODAGENT_CONFIG_FILE=config.local.yaml uv run podcast-agent
"""

#: Matches one `- provider: anthropic` list item and every indented line under
#: it, plus any comment lines immediately above that belong to it.
#:
#: A regex rather than an exact literal on purpose: the anchors in REPLACEMENTS
#: are single lines that are cheap to keep in sync, but these endpoints carry
#: several lines of comment explaining the model choice, and pinning that prose
#: verbatim would break this script every time someone reworded it.
_ANTHROPIC_FALLBACK = re.compile(
    r"""
    (?:^[ ]{8}\#[^\n]*\n)*      # leading comment lines at list-item indent
    ^[ ]{8}-[ ]provider:[ ]anthropic[ ]*\n
    (?:^[ ]{10}[^\n]*\n)*       # the endpoint's own keys, more deeply indented
    """,
    re.MULTILINE | re.VERBOSE,
)

#: A `fallbacks:` key with nothing left under it — YAML would read that as null,
#: which fails validation, so the key goes too.
#:
#: "Nothing left under it" means: not followed by a list item at the endpoint
#: indent, allowing for blank lines in between. The blank line matters — the last
#: tier's fallbacks are followed by one before the next top-level section, and a
#: lookahead that only tolerated a dedented line silently left that key behind.
_EMPTY_FALLBACKS = re.compile(
    r"^[ ]{6}fallbacks:[ ]*\n(?!(?:[ ]*\n)*[ ]{8}-)",
    re.MULTILINE,
)


def strip_anthropic_fallbacks(text: str) -> tuple[str, int]:
    """Remove every anthropic endpoint, and any `fallbacks:` key left empty."""
    text, removed = _ANTHROPIC_FALLBACK.subn("", text)
    text = _EMPTY_FALLBACKS.sub("", text)
    return text, removed


#: (old, new, must_match) — must_match=False tolerates the anchor being absent,
#: which keeps the script working as config.yaml evolves.
REPLACEMENTS: list[tuple[str, str, bool]] = [
    # Host services instead of compose service names.
    ("  url: http://couchdb-podcast:5984", "  url: http://127.0.0.1:5984", True),
    # Writable local paths instead of container mounts.
    ("  digest_dir: /data/digests", "  digest_dir: ./data/digests", True),
    ("  work_dir: /data/work", "  work_dir: ./data/work", True),
    # Loopback only; no macvlan on Docker Desktop.
    (
        "  host: 0.0.0.0               # bound to the container's macvlan LAN IP only",
        "  host: 127.0.0.1             # loopback only on the dev machine",
        True,
    ),
    # large-v3-turbo is a 1.6GB first-run download.
    ("  model: large-v3-turbo", "  model: small.en", True),
    # NOTE: the llm section is intentionally absent from this list. Every tier is
    # cloud in config.yaml while there is no local model host, and rewriting it
    # here would mean local runs stopped exercising the deployed configuration.
    # When an Ollama primary is restored in config.yaml, the local overrides that
    # used to live here (127.0.0.1 api_base, the qwen3.5:9b models with
    # think:false, longer timeouts, smaller token budgets) come back with it.
]


def main() -> int:
    root = pathlib.Path(__file__).resolve().parent.parent
    source = root / "config.yaml"
    target = root / "config.local.yaml"

    text = source.read_text(encoding="utf-8")
    missing: list[str] = []
    for old, new, must_match in REPLACEMENTS:
        if old not in text:
            if must_match:
                missing.append(old.strip().splitlines()[0])
            continue
        text = text.replace(old, new)

    if missing:
        print("config.yaml no longer contains these anchors:", file=sys.stderr)
        for anchor in missing:
            print(f"  {anchor}", file=sys.stderr)
        print("\nUpdate REPLACEMENTS in this script.", file=sys.stderr)
        return 1

    text, dropped = strip_anthropic_fallbacks(text)

    target.write_text(HEADER + "\n" + text, encoding="utf-8")
    print(f"wrote {target.relative_to(root)} from {source.relative_to(root)}")
    print(f"  dropped {dropped} anthropic fallback endpoint(s) — local dev needs no Anthropic key")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
